/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edangie.view.insumo;

/**
 *
 * @author daustinsac
 */
public class InsumoTabs extends javax.swing.JPanel {

    /**
     * Creates new form InsumoTabs
     */
    public InsumoTabs() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        insumoListar2 = new com.edangie.view.insumo.InsumoListar();
        proveedorListar2 = new com.edangie.view.proveedor.ProveedorListar();

        jTabbedPane1.addTab("Insumos", insumoListar2);
        jTabbedPane1.addTab("Proveedores", proveedorListar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 939, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.edangie.view.insumo.InsumoListar insumoListar2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private com.edangie.view.proveedor.ProveedorListar proveedorListar2;
    // End of variables declaration//GEN-END:variables
}
